SELECT A.EMPNO, A.EMPNAME, A.DEPTNAME, A.PATNO
  FROM ACDCMAST A
 WHERE EMPNO IN (
                )
   AND RELATION = '01'
   AND TODATE = '2999-12-31 00:00:00'

-- 정규건진이력 찾기
SELECT A.PATNO
     , A.LASTDATE, TO_CHAR(A.LASTDATE,'YYYY-MM') "MONTH", TO_CHAR(A.LASTDATE,'YYYY') "YEAR"
  FROM (
SELECT A.PATNO, MAX(ORDDATE) LASTDATE
  FROM SMRSV00T A, SMPKGMST B
 WHERE A.PATNO IN (
                  )
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND SUBSTR(B.PKGTYP,1,1) IN ('0','1','2','3','4')
 GROUP BY A.PATNO
       ) A
