-- 정규 건진 VIP
SELECT A.ORDDATE
     , a.patno
     , A.PATNAME, A.SEX, A.AGE, A.PKGCODE, A.PKGNM, A.GUBUN
     , A.CUSTNM, A.DUTYAREANM, A.COMPOS, A.VIPYN, A.AMT
     , MAX(DECODE(B.RELATION||B.USEYN,'1Y',B.TOPATNO,'')) TOPATNO
     , MAX(DECODE(B.RELATION||B.USEYN,'1Y',B.TOPATNAME,'')) TOPATNAME
  FROM (
        SELECT DISTINCT A.RSVNOSM, A.PKGCODE, A.PATNO, A.ORDDATE, A.PATNAME, A.SEX, A.AGE, A.PKGNM, A.VIPYN
             , DECODE(A.CONTNO,'','개인','단체') GUBUN, A.CUSTNM, A.DUTYAREANM, A.COMPOS
             , SUM(C.CREAMT)/1000 AMT
          FROM (
                SELECT A.RSVNOSM, A.PKGCODE, C.pkgnm, A.PATNO, A.ORDDATE, B.PATNAME, B.SEX
                     , TRUNC(MONTHS_BETWEEN(A.ORDDATE,B.BIRTHDAY)/12) AGE, A.CONTNO
                     , B.VIPYN, A.DUTYAREANM, A.COMPOS, D.CUSTNM
                  FROM SMRSV00T A, APPATBAT B, SMPKGMST C, SMCUST0T D
                 WHERE A.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
                   AND A.CANCELTIME IS NULL
                   AND A.PATNO = B.PATNO
                   AND B.VIPYN = 'Y'
                   AND A.PKGCODE = C.PKGCODE
                   AND SUBSTR(C.PKGTYP,1,1) IN ('0','1','2','3','4')
                   AND SUBSTR(A.CONTNO,1,6) = D.CUSTCODE(+)
               ) A
               , SMRCP00T C
         WHERE A.RSVNOSM = C.RSVNOSM
           AND C.RCPTYP IN ('0','7','8')
         GROUP BY A.RSVNOSM, A.PKGCODE, A.PATNO, A.ORDDATE, A.PATNAME, A.SEX, A.AGE, A.CONTNO, A.PKGNM, A.VIPYN, A.CUSTNM, A.DUTYAREANM, A.COMPOS
       ) A
       , SM0TOMST B
 WHERE A.PATNO = B.PATNO(+)
 GROUP BY A.ORDDATE, A.PATNO, A.PATNAME, A.SEX, A.AGE, A.PKGCODE, A.PKGNM, A.GUBUN, A.CUSTNM, A.DUTYAREANM, A.COMPOS, A.VIPYN, A.AMT
 ORDER BY 1,2;

-- 200만원 이상 수납자
SELECT A.ORDDATE
     , a.patno
     , A.PATNAME, A.SEX, A.AGE, A.PKGCODE, A.PKGNM, A.GUBUN, A.CUSTNM, A.DUTYAREANM, A.COMPOS, A.AMT, A.VIPYN,
       MAX(
       CASE WHEN B.TODT IS NULL AND A.ORDDATE > B.FROMDT THEN (SELECT X.HLTHSUGA
                                                                 FROM SM0SUGAT X
                                                                WHERE A.PKGCODE = X.EXAMCODE
                                                                  AND X.TODT IS NULL
                                                              )
            ELSE (SELECT X.HLTHSUGA
                    FROM SM0SUGAT X
                   WHERE A.PKGCODE = X.EXAMCODE
                     AND X.TODT IS NOT NULL
                     AND X.FROMDT < A.ORDDATE
                     AND X.TODT >= A.ORDDATE
                 )
             END
          )/1000   PKGAMT
  FROM (-- 숙박 건진자 제외
SELECT A.RSVNOSM, A.PKGCODE, A.PKGNM, A.PATNO, A.ORDDATE, A.PATNAME, A.SEX, A.AGE, A.VIPYN
     , DECODE(A.CONTNO,'','','단체') GUBUN, A.DUTYAREANM, A.COMPOS, A.CUSTNM
     , SUM(C.CREAMT)/1000 AMT
  FROM (
        SELECT A.RSVNOSM, A.PKGCODE, C.PKGNM, A.PATNO, A.ORDDATE, B.PATNAME, B.SEX
             , TRUNC(MONTHS_BETWEEN(A.ORDDATE,B.BIRTHDAY)/12) AGE, A.CONTNO
             , VIPYN, A.DUTYAREANM, A.COMPOS, D.CUSTNM
          FROM SMRSV00T A, APPATBAT B, SMPKGMST C, SMCUST0T D
         WHERE A.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
           AND A.CANCELTIME IS NULL
           AND A.PATNO = B.PATNO
           AND A.PKGCODE = C.PKGCODE
           AND SUBSTR(C.PKGTYP,1,1) IN ('0','1','2','3','4')
           AND SUBSTR(A.CONTNO,1,6) = D.CUSTCODE(+)
       ) A
       , SMRCP00T C
 WHERE A.RSVNOSM = C.RSVNOSM
   AND C.RCPTYP IN ('0','7','8')
 GROUP BY A.RSVNOSM, A.PKGCODE, A.PKGNM, A.PATNO, A.ORDDATE, A.PATNAME, A.SEX, A.AGE, A.CONTNO, A.VIPYN, A.DUTYAREANM, A.COMPOS, A.CUSTNM
 ORDER BY 4,3
       ) A
       , SM0SUGAT B
 WHERE A.AMT > '1999'
   AND A.PKGCODE = B.EXAMCODE
 GROUP BY A.ORDDATE, A.PATNO, A.PATNAME, A.SEX, A.AGE, A.PKGCODE, A.PKGNM, A.GUBUN, A.DUTYAREANM, A.COMPOS, A.CUSTNM, A.AMT, A.VIPYN;
