SELECT B.EXAMCODE, C.ORDNAME, MIN(TO_NUMBER(B.RSLTNUM)) MIN, MAX(TO_NUMBER(B.RSLTNUM)) MAX
  FROM SMRSV00T A, STRESULT B, MMORDRCT C
 WHERE A.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PATNO = B.PATNO
   AND A.ORDDATE = B.ORDDATE
   AND B.EXAMCODE IN ('BL3118','BL3115','BL3116','BL3113','BL3141','BL314201','SM0101','SM0102','SM0104','SM316001','SM010502')
   AND NVL(B.MODIFYYN,'N') != 'Y'
   AND B.EXAMCODE = C.ORDCODE
 GROUP BY B.EXAMCODE, C.ORDNAME
 ORDER BY 1;

SELECT 'SM0600' EXAMCODE, '혈압' ORDNAME, MIN(TO_NUMBER(A.SBP)) SBPMIN, MAX(TO_NUMBER(A.SBP)) SBPMAX, MIN(TO_NUMBER(A.DBP)) DBPMIN, MAX(TO_NUMBER(A.DBP)) DBPMAX
  FROM (
SELECT A.PATNO, A.ORDDATE, B.RSLTNUM
     , SUBSTR(B.RSLTNUM,1,INSTR(B.RSLTNUM,'/')-1) SBP
     , SUBSTR(B.RSLTNUM,INSTR(B.RSLTNUM,'/')+1) DBP
  FROM SMRSV00T A, STRESULT B
 WHERE A.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PATNO = B.PATNO
   AND A.ORDDATE = B.ORDDATE
   AND B.EXAMCODE = 'SM0600'
   AND NVL(B.MODIFYYN,'N') != 'Y'
       ) A
