-- 내시경 검사인원수
SELECT TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTHS", COUNT(A.PATNO) CNT
  FROM (
SELECT  /*+ INDEX(B MMEXMORT_IDX10) INDEX(B MMEXMORT_IDX12) */
       DISTINCT A.ORDDATE, A.PATNO
  FROM SMRSV00T A, MMEXMORT B
 WHERE A.ORDDATE BETWEEN TO_DATE('20080101','YYYYMMDD') AND TO_DATE('20081231','YYYYMMDD')
   AND A.MEDLOCATFG = 'M'
   AND A.CANCELTIME IS NULL
   AND A.PATNO = B.PATNO
   AND A.ORDDATE = B.ORDDATE
   AND B.ORDCODE LIKE 'BS41%'
   AND B.PATFG = 'G'
       ) A
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM')

-- 수면내시경 건수
SELECT TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTHS", COUNT(A.PATNO) CNT
  FROM SMRSV00T A, SMADD00T B
 WHERE A.ORDDATE BETWEEN TO_DATE('20080101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.MEDLOCATFG = 'M'
   AND A.CANCELTIME IS NULL
   AND A.RSVNOSM = B.RSVNOSM
   AND B.PKGEXAMCODE LIKE 'XMIDA%'
   AND B.CANCELTIME IS NULL
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM')
