SELECT TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTHS", SUM(A.CNT) CNT
  FROM (
SELECT A.ORDDATE, TO_CHAR(A.ORDDATE,'D') GUBUN, COUNT(A.PATNO) CNT
  FROM SMRSV00T A
 WHERE A.ORDDATE BETWEEN TO_DATE('20120101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
 GROUP BY A.ORDDATE, TO_CHAR(A.ORDDATE,'D')
       ) A
 WHERE A.GUBUN = '7'
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM')
