-- 수면
SELECT TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTH", B.PKGEXAMCODE, COUNT(A.PATNO) CNT
  FROM SMRSV00T A, SMADD00T B
 WHERE A.ORDDATE BETWEEN TO_DATE('20110101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.MEDLOCATFG = 'M'
   AND A.RSVNOSM = B.RSVNOSM
   AND B.PKGEXAMCODE LIKE 'XMI%'
   AND B.CANCELTIME IS NULL
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM'), B.PKGEXAMCODE

-- 내시경
SELECT /*+ INDEX(A MMEXMORT_IDX10) INDEX(A MMEXMORT_IDX12) */
       TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTH", A.ORDCODE, A.APPATFG, COUNT(A.PATNO) CNT
  FROM MMEXMORT A
 WHERE A.ORDDATE BETWEEN TO_DATE('20110101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.ORDCODE LIKE 'BS4%'
   AND A.MEDDEPT LIKE 'SM%'
   AND A.MEDLOCATFG = 'M'
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM'), A.ORDCODE, A.APPATFG

-- 암, 여자CT
SELECT /*+ INDEX(A MMEXMORT_IDX10) INDEX(A MMEXMORT_IDX12) */
       TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTH", A.ORDCODE, A.APPATFG, COUNT(A.PATNO) CNT
  FROM MMEXMORT A, SWWORKMT B
 WHERE A.ORDDATE BETWEEN TO_DATE('20110101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.ORDCODE LIKE 'RC%'
   AND A.PATNO = B.PATNO
   AND A.ORDDATE = B.ORDDATE
   AND B.ROOMCODE = 'YF09'
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM'), A.ORDCODE, A.APPATFG



-- 유초
SELECT /*+ INDEX(A MMEXMORT_IDX10) INDEX(A MMEXMORT_IDX12) */
       TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTH", A.ORDCODE, COUNT(A.PATNO) CNT
  FROM MMEXMORT A
 WHERE A.ORDDATE BETWEEN TO_DATE('20110101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.ORDCODE = 'RS1190'
   AND A.MEDDEPT LIKE 'SM%'
   AND A.MEDLOCATFG = 'M'
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM'), A.ORDCODE
