SELECT DISTINCT A.PATNO, B.PATNAME
  FROM MMMEDORT A, APPATBAT B
 WHERE ORDDATE BETWEEN TO_DATE('20120101','YYYYMMDD') AND TO_dATE('20140122','YYYYMMDD')
   AND ORDCODE LIKE 'XZOSTA%'
--   AND MEDDEPT LIKE 'SM%'
   AND NVL(DCYN,'X') = 'N'
   AND EXISTS (
               SELECT 'Y'
                 FROM SMRSV00T X, SMPKGMST Y
                WHERE A.PATNO = X.PATNO
                  AND X.ORDDATE BETWEEN TO_DATE('20120101','YYYYMMDD') AND TO_dATE('20140122','YYYYMMDD')
                  AND X.CANCELTIME IS NULL
                  AND X.PKGCODE = Y.PKGCODE
                  AND Y.PKGTYP = '3A'
              )
   AND A.PATNO = B.PATNO
