SELECT TO_CHAR(A.ORDDATE,'YYYY') "YEAR", A.PKGCODE, COUNT(A.PATNO) CNT
  FROM SMRSV00T A
 WHERE A.ORDDATE BETWEEN TO_DATE('20120101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE IN ('MBS','FBS','YAG','XAG')
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY'), A.PKGCODE
