SELECT A.PATNO, A.ORDDATE, A.PKGCODE, B.ORDCODE, D.ORDNAME
  FROM (
SELECT A.PATNO, A.ORDDATE, A.PKGCODE
     , ROW_NUMBER () OVER (PARTITION BY PATNO ORDER BY A.ORDDATE DESC) RN
  FROM SMRSV00T A
 WHERE A.PATNO IN (
                  )
  AND A.ORDDATE IS NOT NULL
  AND A.CANCELTIME IS NULL
       ) A
     , MMEXMORT B
     , MMORDRCT D
 WHERE A.RN BETWEEN '1' AND '5'
   AND A.PATNO = B.PATNO
   AND A.ORDDATE = B.ORDDATE
   AND B.PATFG = 'G'
   AND B.ORDCODE = D.ORDCODE
UNION ALL
SELECT A.PATNO, A.ORDDATE, A.PKGCODE, C.MATCODE, E.ORDNAME
  FROM (
SELECT A.PATNO, A.ORDDATE, A.PKGCODE
     , ROW_NUMBER () OVER (PARTITION BY PATNO ORDER BY A.ORDDATE DESC) RN
  FROM SMRSV00T A
 WHERE A.PATNO IN (
                  )
  AND A.ORDDATE IS NOT NULL
  AND A.CANCELTIME IS NULL
       ) A
     , SWSNDMAT C
     , MMORDRCT E
 WHERE A.RN BETWEEN '1' AND '5'
   AND A.PATNO = C.PATNO
   AND A.ORDDATE = C.ORDDATE
   AND C.MATCODE = E.ORDCODE
   AND C.EXAMCODE LIKE 'BS%'
 ORDER BY 1, 2 DESC, 4
