-- MD
--검사실별 의사별 검사 건수, 다시 수정 2009.12.01
-- 김영주 방사선사 요청으로 인해 PM기준시간을 1300 -> 1200으로 변경함. 2010.09월 통계부터~~~
SELECT TO_CHAR(A.EXECTIME,'YYYY-MM') "MONTHS",
       A.ORDCODE, B.ORDNAME,
--       TO_CHAR(A.EXECTIME,'HH24:MI') "TIME",
       CASE WHEN TO_CHAR(A.EXECTIME,'HH24MI') < '1200' THEN 'AM'
       ELSE 'PM' END "APM",
       A.MEDLOCATFG,
       A.READDR1||'('||C.USERNAME||')' DR,
       COUNT(A.PATNO)
  FROM MMEXMORT A, MMORDRCT B, CSUSERMT C
 WHERE A.EXECTIME BETWEEN TO_dATE(&D1,'YYYYMMDD') AND TO_dATE(&D2,'YYYYMMDD')+.99999
   AND TO_CHAR(A.EXECTIME,'D') NOT IN ('1','7')
   AND (A.EXAMTYP = 'SR' OR A.ORDCODE = 'BS2231')
   AND A.ORDCODE NOT LIKE 'RC%'
   AND A.ORDCODE NOT LIKE 'RM%'
   AND A.ORDCODE NOT IN ( 'RS2010','RG9214')
   AND A.PATFG = 'G'
   AND A.ORDCODE = B.ORDCODE
   AND A.READDR1 = C.USERID
 GROUP BY TO_CHAR(A.EXECTIME,'YYYY-MM'),
       A.ORDCODE, B.ORDNAME,
--       TO_CHAR(A.EXECTIME,'HH24:MI') ,
       CASE WHEN TO_CHAR(A.EXECTIME,'HH24MI') < '1200' THEN 'AM'
       ELSE 'PM' END ,
       A.MEDLOCATFG,
       A.READDR1||'('||C.USERNAME||')'

-- READ
--의사별 판독건수(판독일 기준) : 영상  ..2009.02.04..CT의 SWWORKMT EXAMTYP을 SR -> SM 변경
SELECT /*+ ORDERED USE_NL(A B) INDEX(A SWWORKMT_IDX9) INDEX(B CSUSERMT_PK) */
       A.PATFG
     , TO_CHAR(A.READTIME,'YYYY-MM') "MONTHS"
     , A.EXAMCODE "EXAM"
     , C.ORDNAME
     , A.MEDCENTER
     , A.READDR1||'-'||B.USERNAME DR
     , COUNT(A.PATNO)
  FROM SWWORKMT A, CSUSERMT B, MMORDRCT C
 WHERE A.READTIME BETWEEN TO_DATE(&D1,'YYYYMMDD') AND TO_DATE(&D2,'YYYYMMDD')+.99999
   AND (A.EXAMTYP = 'SR' OR SUBSTR(A.EXAMCODE,1,2) ='RC')
--   AND A.PATFG = 'G' <-- 2013년 부터 입원, 외래 처방의 경우도 포함하기로 함.
   AND A.READDR1 = B.USERID
   AND B.DEPTCODE LIKE 'SM'
   AND A.EXAMCODE = C.ORDCODE
 GROUP BY  A.PATFG
     , TO_CHAR(A.READTIME,'YYYY-MM')
     , A.EXAMCODE
     , C.ORDNAME
     , A.MEDCENTER
     , A.READDR1||'-'||B.USERNAME

--CNT
--검사실별건수 2009.05.06 하단 CM141 추가
-- 김영주 방사선사 요청으로 인해 PM기준시간을 1300 -> 1200으로 변경함. 2010.09월 통계부터~~~
-- 2011.05.06 수진방 변경으로 인해 쿼리 수정.. CF19 -> CM14, CM13/CF17 -> CF06, CF06 -> CF17, CM11 -> CM13
SELECT TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTHS"
     , DECODE(SUBSTR(C.ORDCODE,1,2),'RC','CT','RM','MRI','NX','NR','NI','NR',E.ORDNAME) EXAM
     , CASE WHEN NVL(TO_CHAR(examsttime,'HH24MI'),'0000') < '1200' THEN 'AM'
            ELSE 'PM'
       END "TIME"
     , A.MEDLOCATFG
     , A.eptexamrmcode
     , DECODE(SUBSTR(C.ORDCODE,1,2),'RC','CT','RM','MRI','NX','NR','NI','NR',E.ORDNAME)||';'||A.eptexamrmcode "EXE_R"
     , COUNT(A.PATNO) CNT
  FROM SMMEDSTT A, SMRSV00T B, MMEXMORT C, SMORDRCT D, MMORDRCT E
 WHERE A.ORDDATE BETWEEN TO_DATE(&D1,'YYYYMMDD') AND TO_DATE(&D2,'YYYYMMDD')
   AND TO_CHAR(A.ORDDATE,'D') NOT IN ('1','7')
   AND A.examepttyp NOT IN ('N','S')
   AND A.RSVNOSM = B.RSVNOSM
   AND B.PATNO = C.PATNO
   AND B.ORDDATE = C.ORDDATE
   AND (C.ORDCODE in (
                      'RG012L','RG010P','RF1040','RG9230','RS1010','RG9214','RS1172','RS1170','RS1170A','RS1140'
                     ,'BS2231','RS1190','NX1001','NX1002','BS7001','NI0702','RG9270','RG923C','RG927C','SM2002'
                     )
       OR
        SUBSTR(C.ORDCODE,1,2) IN ('RC','RM')
       )
   AND C.ORDCODE = D.EXAMCODE
   AND C.ORDCODE = E.ORDCODE
   AND A.eptexamrmcode  IN ( D.MEDROOM1, D.MEDROOM2, D.MEDROOM3, D.PMMEDROOM1, D.PMMEDROOM2, D.PMMEDROOM3)
   AND C.PATFG = 'G'
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM'),
          DECODE(SUBSTR(C.ORDCODE,1,2),'RC','CT','RM','MRI','NX','NR','NI','NR',E.ORDNAME),
          CASE WHEN NVL(TO_CHAR(examsttime,'HH24MI'),'0000') < '1200' THEN 'AM'
       ELSE 'PM' END, A.MEDLOCATFG, A.eptexamrmcode
UNION ALL
SELECT TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTHS"
     , 'CAROTID_SONO' EXAM
     , DECODE(A.eptexamrmcode,'AR20','AM','AR201','PM','CF13','ALL','CM13','ALL') "TIME"
     , A.MEDLOCATFG
     , A.eptexamrmcode
     , 'CAROTID_SONO'||';'||A.eptexamrmcode "EXE_R"
     , COUNT(A.PATNO)
  FROM SMMEDSTT A, SMRSV00T B
 WHERE A.ORDDATE BETWEEN TO_DATE(&D1,'YYYYMMDD') AND TO_DATE(&D2,'YYYYMMDD')
   AND TO_CHAR(A.ORDDATE,'D') NOT IN ('1','7')
   AND A.examepttyp NOT IN ('N','S')
   AND A.eptexamrmcode IN ('AR20','AR201','CF13','CM13')
   AND A.RSVNOSM = B.RSVNOSM
  GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM'), A.MEDLOCATFG, A.eptexamrmcode, DECODE(A.eptexamrmcode,'AR20','AM','AR201','PM','CF13','ALL','CM13','ALL')
