-- 영상검사 건수
SELECT TO_CHAR(A.EXECTIME,'YYYY-MM-DD') EXECDATE, A.ORDCODE, B.ORDNAME
     , CASE WHEN NVL(TO_CHAR(A.EXECTIME,'HH24MI'),'0000') < '1200' THEN 'AM'
            ELSE 'PM'
       END "TIME"
     , C.ROOMCODE
     , COUNT(A.PATNO) CNT
  FROM MMEXMORT A, MMORDRCT B, SWWORKMT C
 WHERE A.EXECTIME BETWEEN TO_dATE(&D1,'YYYYMMDD') AND TO_dATE(&D2,'YYYYMMDD')+.99999
   AND A.PATFG = 'G'
   AND (A.EXAMTYP = 'SR' OR A.ORDCODE = 'BS2231' OR A.ORDCODE = 'SM2002' or a.ordcode = 'NX1001' or a.ordcode = 'RF1040')
   AND A.ORDCODE = B.ORDCODE
   AND A.PATNO = C.PATNO(+)
   AND A.ORDDATE = C.ORDDATE(+)
   AND A.ORDCODE = C.EXAMCODE(+)
 GROUP BY TO_CHAR(A.EXECTIME,'YYYY-MM-DD'), A.ORDCODE, B.ORDNAME
     , CASE WHEN NVL(TO_CHAR(A.EXECTIME,'HH24MI'),'0000') < '1200' THEN 'AM'
            ELSE 'PM'
       END
     , C.ROOMCODE
