-- CNT
SELECT c.pkgtyp, COUNT(A.PATNO) CNT
  FROM SMRSV00T A, SMQWEBMT B, SMPKGMST C
 WHERE A.ORDDATE BETWEEN TO_DATE('20130901','YYYYMMDD') AND TO_dATE('20140228','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = C.PKGCODE
   AND SUBSTR(C.PKGTYP,1,1) IN ('0','1','2','3','4')
   AND A.RSVNOSM = B.RSVNOSM
   AND NVL(B.SKIPYN,'N') != 'Y'
   AND B.REJTTIME IS NULL
   AND B.SENDTIME IS NOT NULL
 group by c.pkgtyp

-- 전체수진인원
SELECT b.pkgtyp, COUNT(A.PATNO) CNT
  FROM SMRSV00T A, SMPKGMST B
 WHERE A.ORDDATE BETWEEN TO_DATE('20130901','YYYYMMDD') AND TO_dATE('20140228','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND SUBSTR(B.PKGTYP,1,1) IN ('0','1','2','3','4')
 group by b.pkgtyp;
