SELECT TO_CHAR(A.ORDDATE,'YYYY') "YEAR", a.pkgtyp, A.PKGEXAMCODE, SUM(SM_AMT) ADDAMT
  FROM (
SELECT A.ORDDATE, A.PATNO, C.PKGEXAMCODE, b.pkgtyp
     , (
        select NVL(SUM(DECODE(X.PSNGRPTYP,'G',DECODE(X.RCPTYP,'0',X.CREAMT),X.CREAMT)),'0')
          from smrcp00t x
         where x.rsvnosm = C.rsvnosm
           AND X.PKGEXAMCODE = C.PKGEXAMCODE
       ) sm_amt
  FROM SMRSV00T A, SMPKGMST B, SMADD00T C
 WHERE A.ORDDATE BETWEEN TO_DATE('20090101','YYYYMMDD') AND TO_DATE('20091231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND SUBSTR(B.PKGTYP,1,1) IN ('0','1','2','3','4')
   AND A.RSVNOSM = C.RSVNOSM
   AND C.EXAMTYP = '1'
   AND C.CANCELTIME IS NULL
       ) A
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY'), a.pkgtyp, A.PKGEXAMCODE
