/* WITH SMC 소식지 발송 예정자 */
SELECT DECODE(B.PKGTYP,'4A','1.FirstClass','4B','2.숙박건진','1P','3.Premium건진') PKGGUBUN
     , SUBSTR(A.PATNO,1,5)||'***' PATNO
     , C.PATNAME, C.SEX, C.RESNO1||'-'||C.RESNO2 RESNO
  FROM SMRSV00T A, SMPKGMST B, APPATBAT C
 WHERE A.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND B.PKGTYP IN ('4A','4B','1P')
   AND B.PKGCODE NOT IN ('PY45','PX50','VMF','VFF')
   AND A.PATNO = C.PATNO
UNION ALL
SELECT '4.건진VIP' PKGGUBUN, SUBSTR(PATNO,1,5)||'***' PATNO, PATNAME, SEX, RESNO1||'-'||RESNO2 RESNO
  FROM APPATBAT
 WHERE PATNO IN (
                )
 ORDER BY 1,2,3

/* WITH SMC 소식지 발송 예정자 */
SELECT '건진' "구분"--, DECODE(B.PKGTYP,'4A','1.FirstClass','4B','2.숙박건진','1P','3.Premium건진') PKGGUBUN
     , C.PATNAME
     , A.PATNO
     , '' CUSTNM
     , A.COMPOS
     , C.ZIPADDR||' '||C.ADDRESS ADDRESS
  FROM SMRSV00T A, SMPKGMST B, APPATBAT C
 WHERE A.ORDDATE BETWEEN TO_DATE(&FROMDT,'YYYYMMDD') AND TO_DATE(&TODT,'YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND B.PKGTYP IN ('4A','4B','1P')
   AND B.PKGCODE NOT IN ('PY45','PX50','VMF','VFF')
   AND A.PATNO = C.PATNO
UNION ALL
SELECT '건진' "구분"--, '4.건진VIP' PKGGUBUN
     , PATNAME
     , PATNO
     , '' CUSTNM
     , '' COMPOS
     , ZIPADDR||' '||ADDRESS ADDRESS
  FROM APPATBAT
 WHERE PATNO IN (
                )
 ORDER BY 1,2,3
