SELECT TO_CHAR(A.ORDDATE,'YYYY-MM'), B.CUSTCODE, B.CUSTNM, COUNT(A.PATNO) CNT
  FROM SMRSV00T A, SMCUST0T B, SMPKGMST C, CCCOMCDT D
 WHERE A.ORDDATE BETWEEN TO_DATE('20140201','YYYYMMDD') AND TO_DATE('20140228','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.CONTNO IS NOT NULL
   AND SUBSTR(A.CONTNO,1,6) = B.CUSTCODE
   AND A.PKGCODE = C.PKGCODE
   AND D.GRPCODE = 'SMM92'
   AND C.PKGTYP = D.CODE
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM'), B.CUSTCODE, B.CUSTNM
 ORDER BY 4 DESC;
