SELECT distinct A.ORDDATE, A.PATNO2, A.PKGCODE, A.REXAMYN, A.REXAMEXEYN, B.EPTDATE, A.RISKYN, A.CANCERYN
  FROM (
SELECT A.ORDDATE, A.RSVNOSM
     , CASE WHEN LENGTH(SUBSTR(A.PATNO,1,5)||((789+SUBSTR(A.PATNO,6))||SUBSTR(A.PATNO,6))) = '11'
            THEN '0'||SUBSTR(A.PATNO,1,5)||((789+SUBSTR(A.PATNO,6))||SUBSTR(A.PATNO,6))
       ELSE SUBSTR(A.PATNO,1,5)||((789+SUBSTR(A.PATNO,6))||SUBSTR(A.PATNO,6)) END PATNO2
     , A.PKGCODE
     , (SELECT DISTINCT 'Y'
          FROM SMREXAMT X
         WHERE A.RSVNOSM = X.RSVNOSM
           AND X.REEXAMTYP IN ('1','2')
       ) REXAMYN
     , (SELECT DISTINCT 'Y'
          FROM SMREXAMT X
         WHERE A.RSVNOSM = X.RSVNOSM
           AND X.REEXAMTYP IN ('1','2')
           AND X.EXAMEXETIME IS NOT NULL
       ) REXAMEXEYN
     , (SELECT DISTINCT 'Y'
          FROM SMDIS00T X, CCCOMCDT Y
         WHERE A.RSVNOSM = X.RSVNOSM
           AND X.DISTYP = 'R'
           AND Y.GRPCODE = 'SM306'
           AND X.EXAMCODE||X.DECICODE = Y.OPTION1||Y.OPTION2
           AND Y.OPTION10 = 'Y'
       ) RISKYN
     , (SELECT DISTINCT 'Y'
          FROM SMDIS00T X
         WHERE A.RSVNOSM = X.RSVNOSM
           AND X.DISTYP = 'C'
       ) CANCERYN
  FROM SMRSV00T A, SMPKGMST B
 WHERE A.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND B.PKGTYP = '3A'
       ) A
     , (
SELECT A.*, B.EPTDATE
  FROM (
SELECT A.ORDDATE, A.RSVNOSM
     , CASE WHEN LENGTH(SUBSTR(A.PATNO,1,5)||((789+SUBSTR(A.PATNO,6))||SUBSTR(A.PATNO,6))) = '11'
            THEN '0'||SUBSTR(A.PATNO,1,5)||((789+SUBSTR(A.PATNO,6))||SUBSTR(A.PATNO,6))
       ELSE SUBSTR(A.PATNO,1,5)||((789+SUBSTR(A.PATNO,6))||SUBSTR(A.PATNO,6)) END PATNO2
     , A.PKGCODE
     , (SELECT DISTINCT 'Y'
          FROM SMREXAMT X
         WHERE A.RSVNOSM = X.RSVNOSM
           AND X.REEXAMTYP IN ('1','2')
       ) REXAMYN
     , (SELECT DISTINCT 'Y'
          FROM SMREXAMT X
         WHERE A.RSVNOSM = X.RSVNOSM
           AND X.REEXAMTYP IN ('1','2')
           AND X.EXAMEXETIME IS NOT NULL
       ) REXAMEXEYN
     , (SELECT DISTINCT 'Y'
          FROM SMDIS00T X, CCCOMCDT Y
         WHERE A.RSVNOSM = X.RSVNOSM
           AND X.DISTYP = 'R'
           AND Y.GRPCODE = 'SM306'
           AND X.EXAMCODE||X.DECICODE = Y.OPTION1||Y.OPTION2
           AND Y.OPTION10 = 'Y'
       ) RISKYN
     , (SELECT DISTINCT 'Y'
          FROM SMDIS00T X
         WHERE A.RSVNOSM = X.RSVNOSM
           AND X.DISTYP = 'C'
       ) CANCERYN
  FROM SMRSV00T A, SMPKGMST B
 WHERE A.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND B.PKGTYP = '3A'
       ) A
     , SMREXAMT B
 WHERE A.RSVNOSM = B.RSVNOSM(+)
   AND B.REEXAMTYP IN ('1','2')
       ) B
 WHERE A.RSVNOSM = B.RSVNOSM(+)
 ORDER BY 1,3;