-- 내시경
SELECT /*+ INDEX(A MMEXMORT_IDX10) INDEX(A MMEXMORT_IDX12) */
       TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTH", A.ORDCODE, A.APPATFG, COUNT(A.PATNO) CNT
  FROM MMEXMORT A
 WHERE A.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.ORDCODE LIKE 'BS4%'
   AND A.MEDDEPT LIKE 'SM%'
--   AND A.MEDLOCATFG = 'C'
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM'), A.ORDCODE, A.APPATFG
