SELECT TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTH", COUNT(A.PATNO) CNT
  FROM (
SELECT A.ORDDATE, A.PATNO, COUNT(B.ORDDATE) CNT
  FROM (
SELECT *
  FROM SMRSV00T A, SMPKGMST B
 WHERE A.ORDDATE BETWEEN TO_DATE('20130601','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND B.PKGTYP = '0'
       ) A
     , SMRSV00T B
     , SMPKGMST C
 WHERE A.PATNO = B.PATNO
   AND B.CANCELTIME IS NULL
   AND B.ORDDATE IS NOT NULL
   AND A.ORDDATE >= B.ORDDATE
   AND B.PKGCODE = C.PKGCODE
   AND C.PKGTYP = '0'
 GROUP BY A.ORDDATE, A.PATNO
       ) A
 WHERE A.CNT > 9
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM')
