SELECT TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTHS", COUNT(A.PATNO) CNT
  FROM SMRSV00T A
 WHERE A.ORDDATE BETWEEN TO_DATE('20070101','YYYYMMDD') AND TO_DATE('20140531','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.DCCODESM = 'A02'
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM');
