-- READ
-- 의사별 판독건수(판독일 기준) : 영상  ..2009.02.04..CT의 SWWORKMT EXAMTYP을 SR -> SM 변경
 SELECT /*+ ORDERED USE_NL(A B) INDEX(A SWWORKMT_IDX9) INDEX(B CSUSERMT_PK) */
         TO_CHAR(A.READTIME,'YYYY-MM') READ_DAY
       , A.PATFG
--       , A.ORDDATE
       , A.EXAMCODE "EXAM"
       , C.ORDNAME
       , A.MEDCENTER
       , A.READDR1||'-'||B.USERNAME DR
       , COUNT(A.PATNO) CNT
  FROM SWWORKMT A, CSUSERMT B, MMORDRCT C
  WHERE A.READTIME BETWEEN TO_DATE(&D1,'YYYYMMDD') AND TO_DATE(&D2,'YYYYMMDD')+.99999
    AND (A.EXAMTYP = 'SR' OR SUBSTR(A.EXAMCODE,1,2) ='RC')
   AND A.PATFG = 'G' -- 건진처방만 고려
   AND A.READDR1 = B.USERID
   AND B.USERID = '112022'
   AND A.EXAMCODE = C.ORDCODE
 GROUP BY  A.PATFG, A.EXAMCODE , C.ORDNAME,  A.MEDCENTER ,
       TO_CHAR(A.READTIME,'YYYY-MM'), A.READDR1, B.USERNAME
