SELECT TO_CHAR(SENDTIME,'YYYY-MM-DD') "DAY", COUNT(RSVNOSM) CNT
  FROM SMQWEBMT
 WHERE SENDTIME BETWEEN TO_DATE('20140501','YYYYMMDD') AND TO_DATE('20140531','YYYYMMDD')+0.99999
   AND REJTTIME IS NULL
 GROUP BY TO_CHAR(SENDTIME,'YYYY-MM-DD')
