 SELECT A.ORDDATE, A.PATNO, D.PATNAME, D.SEX,
       TRUNC(MONTHS_BETWEEN(A.ORDDATE, D.birthday)/12) AGE,
       MAX(DECODE(C.EXAMCODE, 'BS4100',C.readdr1,'')) DR_ID,
    MAX(DECODE(C.EXAMCODE, 'BS4100',E.USERNAME,'')) DR_NM,
    MAX(DECODE(C.EXAMCODE, 'BS4100',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),'')) ENDO,
    MAX(DECODE(SUBSTR(C.EXAMCODE,1,7), 'BP1A01A',C.readdr1, 'BP1A151',C.readdr1, 'BP1A155',C.readdr1,'')) BP_ID,
    MAX(DECODE(SUBSTR(C.EXAMCODE,1,7), 'BP1A01A',E.USERNAME,'BP1A151',E.USERNAME,'BP1A155',E.USERNAME,'')) BP_NM,
    MAX(DECODE(SUBSTR(C.EXAMCODE,1,7), 'BP1A01A',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),
                                       'BP1A151',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),
                                       'BP1A155',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),'')) BIOPSY
  FROM SMRSV00T A, SMRSLTCT B, STRESULT C, APPATBAT D, CSUSERMT E
 WHERE A.ORDDATE BETWEEN TO_DATE(&D1,'YYYYMMDD') AND TO_DATE(&D2,'YYYYMMDD')
  AND A.PATNO = B.PATNO
  AND A.ORDDATE = B.ORDDATE
  AND SUBSTR(B.examcode,1,7)  IN ('BP1A01A','BP1A151','BP1A155')
  AND B.rsltcode IN ('D406','G052','G100','G101','G102','G103','G120','G301','G303','G304','G051','G104','G080')
--G051,G104,G080  추가 2011.01.19 나윤주
  AND A.PATNO = C.PATNO
  AND A.ORDDATE = C.ORDDATE
  AND (C.EXAMCODE IN ('BS4100', 'BP1A01A')
      OR SUBSTR(C.EXAMCODE,1,7) IN ('BP1A151','BP1A155'))
  AND NVL(C.modifyyn,'N') = 'N'
  AND A.PATNO = D.PATNO
  AND C.readdr1  = E.USERID
  GROUP BY  A.ORDDATE, A.PATNO, D.PATNAME, D.SEX,
       TRUNC(MONTHS_BETWEEN(A.ORDDATE, D.birthday)/12)

 SELECT A.ORDDATE, A.PATNO, D.PATNAME, D.SEX,
       TRUNC(MONTHS_BETWEEN(A.ORDDATE, D.birthday)/12) AGE,
       MAX(DECODE(C.EXAMCODE, 'BS4141',C.readdr1,'')) DR_ID,
    MAX(DECODE(C.EXAMCODE, 'BS4141',E.USERNAME,'')) DR_NM,
    MAX(DECODE(C.EXAMCODE, 'BS4141',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),'')) ENDO,
    MAX(DECODE(SUBSTR(C.EXAMCODE,1,7), 'BP1A01B',C.readdr1, 'BP1A152',C.readdr1,'')) BP_ID,
    MAX(DECODE(SUBSTR(C.EXAMCODE,1,7), 'BP1A01B',E.USERNAME, 'BP1A152',E.USERNAME,'')) BP_NM,
    MAX(DECODE(SUBSTR(C.EXAMCODE,1,7), 'BP1A01B',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),
                                       'BP1A152',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),'')) BIOPSY
  FROM SMRSV00T A, SMRSLTCT B, STRESULT C, APPATBAT D, CSUSERMT E
 WHERE A.ORDDATE BETWEEN TO_DATE(&D1,'YYYYMMDD') AND TO_DATE(&D2,'YYYYMMDD')
  AND A.PATNO = B.PATNO
  AND A.ORDDATE = B.ORDDATE
  AND SUBSTR(B.examcode,1,7)  IN ( 'BP1A01B','BP1A152' )
  AND B.rsltcode IN ('060','091','110')
  AND A.PATNO = C.PATNO
  AND A.ORDDATE = C.ORDDATE
  AND (C.EXAMCODE IN ('BS4141', 'BP1A01B')
       OR SUBSTR(C.EXAMCODE,1,7) = 'BP1A152')
  AND NVL(C.modifyyn,'N') = 'N'
  AND A.PATNO = D.PATNO
  AND C.readdr1  = E.USERID
  GROUP BY  A.ORDDATE, A.PATNO, D.PATNAME, D.SEX,
       TRUNC(MONTHS_BETWEEN(A.ORDDATE, D.birthday)/12)

 SELECT A.ORDDATE, A.PATNO, D.PATNAME, D.SEX,
       TRUNC(MONTHS_BETWEEN(A.ORDDATE, D.birthday)/12) AGE,
       MAX(DECODE(C.EXAMCODE, 'BS4152',C.readdr1,'')) DR_ID,
    MAX(DECODE(C.EXAMCODE, 'BS4152',E.USERNAME,'')) DR_NM,
    MAX(DECODE(C.EXAMCODE, 'BS4152',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),'')) ENDO,
    MAX(DECODE(SUBSTR(C.EXAMCODE,1,7), 'BP1A01C',C.readdr1, 'BP1A153',C.readdr1,'')) BP_ID,
    MAX(DECODE(SUBSTR(C.EXAMCODE,1,7), 'BP1A01C',E.USERNAME, 'BP1A153',E.USERNAME,'')) BP_NM,
    MAX(DECODE(SUBSTR(C.EXAMCODE,1,7), 'BP1A01C',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),
                                       'BP1A153',REPLACE(TO_CHAR(C.RSLTTEXT),CHR(13),''),'')) BIOPSY
  FROM SMRSV00T A, SMRSLTCT B, STRESULT C, APPATBAT D, CSUSERMT E
 WHERE A.ORDDATE BETWEEN TO_DATE(&D1,'YYYYMMDD') AND TO_DATE(&D2,'YYYYMMDD')
  AND A.PATNO = B.PATNO
  AND A.ORDDATE = B.ORDDATE
  AND SUBSTR(B.examcode,1,7) IN ( 'BP1A01C','BP1A153')
  AND B.rsltcode IN ('060','091','110')
  AND A.PATNO = C.PATNO
  AND A.ORDDATE = C.ORDDATE
  AND (C.EXAMCODE IN ('BS4152', 'BP1A01C')
      OR SUBSTR(C.EXAMCODE,1,7) = 'BP1A153')
  AND NVL(C.modifyyn,'N') = 'N'
  AND A.PATNO = D.PATNO
  AND C.readdr1  = E.USERID
  GROUP BY  A.ORDDATE, A.PATNO, D.PATNAME, D.SEX,
       TRUNC(MONTHS_BETWEEN(A.ORDDATE, D.birthday)/12)
