SELECT TO_CHAR(A.FSTDATE,'YYYY-MM') "MONTH", COUNT(A.PATNO)  CNT
  FROM (
        SELECT A.PATNO, MIN(B.ORDEPTDATE) FSTDATE
          FROM (
                SELECT *
                  FROM SMRSV00T A, SMPKGMST B
                 WHERE A.ORDEPTDATE BETWEEN TO_DATE('20140901','YYYYMMDD') AND TO_DATE('20141031','YYYYMMDD')
                   AND A.CANCELTIME IS NULL
                   AND A.PKGCODE = B.PKGCODE
                   AND SUBSTR(B.PKGTYP,1,1) IN ('1')
               ) A
             , SMRSV00T B
             , SMPKGMST C
         WHERE A.PATNO = B.PATNO
           AND A.ORDEPTDATE > = B.ORDEPTDATE
           AND B.CANCELTIME IS NULL
           AND B.PKGCODE = C.PKGCODE
           AND SUBSTR(C.PKGTYP,1,1) IN ('0','1','2','3','4')
         GROUP BY A.PATNO
       ) A
 WHERE A.FSTDATE BETWEEN TO_DATE('20140901','YYYYMMDD') AND TO_DATE('20141031','YYYYMMDD')
 GROUP BY TO_CHAR(A.FSTDATE,'YYYY-MM')
