--원무 기초
SELECT TO_CHAR(A.ORDDATE,'YYYY')"YEAR", A.PKG, A.GUBUN, A.AREA, COUNT(A.PATNO2) CNT
  FROM (
SELECT A.ORDDATE, TO_CHAR(A.ORDDATE,'MM') MON, A.PATNO
     , DECODE(SUBSTR(C.PKGTYP,1,1),'4','',DECODE(A.CONTNO,'','1.개인','2.단체')) GUBUN
     , CASE WHEN LENGTH(SUBSTR(A.PATNO,1,5)||((789+SUBSTR(A.PATNO,6))||SUBSTR(A.PATNO,6))) = '11'
            THEN '0'||SUBSTR(A.PATNO,1,5)||((789+SUBSTR(A.PATNO,6))||SUBSTR(A.PATNO,6))
       ELSE SUBSTR(A.PATNO,1,5)||((789+SUBSTR(A.PATNO,6))||SUBSTR(A.PATNO,6))
       END PATNO2
     , B.PATNAME, B.SEX,
       TRUNC(MONTHS_BETWEEN(A.ORDDATE, B.BIRTHDAY)/12) AGE,
       B.ZIPCODE "ADD",
       DECODE(SUBSTR(B.ZIPCODE,1,3),'135','1.KANGNAM','137','2.SEOCHO','138','3.SONGPA',
              DECODE(SUBSTR(B.ZIPCODE,1,1),'1','4.SEOUL_ETC','4','5.KYUNGKI','6','6.KYUNGNAM','7','7.KYUNGBOOK','8.ETC')) AREA,
       DECODE(SUBSTR(C.PKGTYP,1,1),'0','2.기타정규PKG','1','2.기타정규PKG','2','2.기타정규PKG','3','2.기타정규PKG','4','1.숙박','5','5.특화','6','6.생습') PKG
  FROM SMRSV00T A, APPATBAT B, SMPKGMST C
 WHERE A.ORDDATE BETWEEN TO_DATE('20090101','YYYYMMDD') AND TO_DATE('20091231','YYYYMMDD')
  AND A.CANCELTIME IS NULL
  AND A.PATNO = B.PATNO
  AND A.PKGCODE = C.PKGCODE
  AND SUBSTR(C.PKGTYP,1,1) IN ('0','1','2','3','4')
       ) A
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY'), A.GUBUN, A.PKG, A.AREA
 ORDER BY 2,3,4
