SELECT *
  FROM MMMEDORT A
 WHERE ORDDATE BETWEEN TO_DATE('20131001','YYYYMMDD') AND TO_dATE('20140131','YYYYMMDD')
   AND ORDCODE LIKE 'XINFT%'
   AND MEDDEPT LIKE 'SM%'
   AND NVL(DCYN,'X') = 'N'
   AND EXISTS (
               SELECT 'Y'
                 FROM SMRSV00T X
                WHERE A.PATNO = X.PATNO
                  AND X.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_dATE('20131231','YYYYMMDD')
                  AND X.CANCELTIME IS NULL
                  AND X.PKGCODE LIKE 'MM%'
              );
