SELECT C.*--C.PATNO, SUM(RCPAMT)
  FROM SMRSV00T A, SMPKGMST D, MMEXMORT B, ACOPCALT C
 WHERE A.PATNO = ''
   AND A.ORDDATE BETWEEN TO_DATE('20140801','YYYYMMDD') AND TO_DATE('20140801','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = D.PKGCODE
   AND D.PKGTYP = '8'
   AND A.PATNO = B.PATNO
   AND A.ORDDATE = B.ORDDATE
   AND B.PATFG = 'G'
   AND B.PATNO = C.PATNO
   AND B.ORDDATE = C.ORDDATE
   AND B.ORDSEQNO = C.ORDSEQNO
   AND C.RCPSTAT != '7'
--   and (c.sugacode = 'CG2702'
--       or
--        c.sugacode like 'SM%'
--       )
 ORDER BY C.ORDCODE, C.SUGACODE
--   AND C.REJTTIME IS NOT NULL
-- GROUP BY C.PATNO
