SELECT TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTH", C.USERID, C.USERNAME, B.EXAMCODE, D.ORDNAME EXAMNM, COUNT(A.PATNO) CNT
  FROM SMRSV00T A, STRESULT B, CSUSERMT C, MMORDRCT D
 WHERE A.ORDDATE BETWEEN TO_DATE('20110101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PATNO = B.PATNO
   AND A.ORDDATE = B.ORDDATE
   AND NVL(B.MODIFYYN,'N') != 'Y'
   AND B.WRITERID = C.USERID
   AND C.DEPTCODE = 'SM'
   AND C.JIKJONG IN ('HAD','AAH')
   AND B.EXAMCODE = D.ORDCODE
 GROUP BY TO_CHAR(A.ORDDATE,'YYYY-MM'), C.USERID, C.USERNAME, B.EXAMCODE, D.ORDNAME;
