SELECT *
  FROM MMMEDORT A
 WHERE ORDDATE BETWEEN TO_DATE('20131001','YYYYMMDD') AND TO_dATE('20140131','YYYYMMDD')
   AND ORDCODE LIKE 'XINFT%'
   AND MEDDEPT LIKE 'SM%'
   AND NVL(DCYN,'X') = 'N'
   AND EXISTS (
               SELECT 'Y'
                 FROM SMRSV00T X, SMPKGMST Y
                WHERE A.PATNO = X.PATNO
                  AND X.ORDDATE BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_dATE('20131231','YYYYMMDD')
                  AND X.CANCELTIME IS NULL
                  AND X.PKGCODE = Y.PKGCODE
                  AND SUBSTR(Y.PKGTYP,1,1) IN ('0','1','2','3','4')
              );