SELECT TO_CHAR(A.EXECTIME,'YYYY-MM-DD')||'('||DECODE(TO_CHAR(A.EXECTIME,'D'),'2','MON','3','TUE','4','WED','5','THU','6','FRI','7','SAT','1','SUN') ||')'  "DAY"
     , A.ROOMCODE
     , CASE
            WHEN TO_CHAR(A.EXECTIME,'HH24MI') < '0929' THEN '2. 기타시간'
            WHEN TO_CHAR(A.EXECTIME,'HH24MI') > '1230' THEN '2. 기타시간'
       ELSE '1.지정시간' END TIMEGUBUN
     , NVL(A.EQIPCODE,'미입력') EQIPCODE
     , A.EXAMCODE
     , B.ORDNAME
     , COUNT(A.PATNO)  CNT
  FROM SWWORKMT A
     , MMORDRCT B
 WHERE A.EXECTIME BETWEEN TO_DATE('20140101','YYYYMMDD') AND TO_DATE('20140831','YYYYMMDD') + 0.99999
   AND A.EXAMCODE IN ('BS4141','BS4411','BS4416GSM','BS4417')
   AND A.MEDDEPT LIKE 'SM%'
   AND A.ROOMCODE IN ('SM','CSM')
   AND A.EXAMCODE = B.ORDCODE
 GROUP BY TO_CHAR(A.EXECTIME,'YYYY-MM-DD')||'('||DECODE(TO_CHAR(A.EXECTIME,'D'),'2','MON','3','TUE','4','WED','5','THU','6','FRI','7','SAT','1','SUN') ||')'
     , A.ROOMCODE
     , NVL(A.EQIPCODE,'미입력')
     , A.EXAMCODE
     , B.ORDNAME
     , CASE
            WHEN TO_CHAR(A.EXECTIME,'HH24MI') < '0929' THEN '2. 기타시간'
            WHEN TO_CHAR(A.EXECTIME,'HH24MI') > '1230' THEN '2. 기타시간'
       ELSE '1.지정시간' END
 ORDER BY 1,2,3,5,4
