SELECT TO_CHAR(EXECTIME,'YYYY-MM') "MONTHS", ROOMCODE, COUNT(PATNO) CNT
  FROM SWWORKMT
 WHERE EXECTIME BETWEEN TO_DATE('20130101','YYYYMMDD') AND TO_DATE('20131231','YYYYMMDD')+0.99999
   AND EXAMCODE ='BS4100'
   AND ROOMCODE IN ('SM','CSM')
 GROUP BY TO_CHAR(EXECTIME,'YYYY-MM'), ROOMCODE;
 
