SELECT *
  FROM MMMEDORT A
 WHERE ORDDATE BETWEEN TO_DATE('20140901','YYYYMMDD') AND TO_dATE('20141026','YYYYMMDD')
   AND ORDCODE LIKE 'XINFT%'
   AND MEDDEPT LIKE 'SM%'
   AND NVL(DCYN,'X') = 'N'
   AND EXISTS (
               SELECT 'Y'
                 FROM SMRSV00T X, SMPKGMST Y
                WHERE A.PATNO = X.PATNO
                  AND X.ORDDATE BETWEEN TO_DATE('20140101','YYYYMMDD') AND TO_dATE('20140831','YYYYMMDD')
                  AND X.CANCELTIME IS NULL
                  AND X.PKGCODE = Y.PKGCODE
                  AND Y.PKGTYP = '1'
              );
