SELECT DISTINCT '추가/선택항목' GUBUN, A.ORDCODE, B.ORDNAME
  FROM SMPKGMDT A, MMORDRCT B
 WHERE A.PKGCODE LIKE 'MM%'
   AND A.EXAMTYP IN ('1','2')
   AND A.ORDCODE = B.ORDCODE;

SELECT DISTINCT '맞춤설계항목' GUBUN, OPTION3, OPTION4, OPTION7, OPTION8
  FROM CCCOMCDT
 WHERE GRPCODE = 'SMM16';

SELECT DISTINCT '안내문출력' GUBUN, CODENAME, OPTION1, OPTION2
  FROM CCCOMCDT
 WHERE GRPCODE = 'SMM35';
