/* WITH SMC 소식지 발송 예정자 */
SELECT DECODE(B.PKGTYP,'4A','1.FirstClass','4B','2.숙박건진','1P','3.Premium건진') PKGGUBUN
     , SUBSTR(A.PATNO,1,5)||'***' PATNO
     , C.PATNAME, C.SEX, C.RESNO1||'-'||C.RESNO2 RESNO
  FROM SMRSV00T A, SMPKGMST B, APPATBAT C
 WHERE A.ORDDATE BETWEEN TO_DATE('20140101','YYYYMMDD') AND TO_DATE('20141031','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND B.PKGTYP IN ('4A','4B','1P')
   AND B.PKGCODE NOT IN ('PY45','PX50','VMF','VFF')
   AND A.PATNO = C.PATNO
UNION ALL
SELECT '4.건진VIP' PKGGUBUN, SUBSTR(PATNO,1,5)||'***' PATNO, PATNAME, SEX, RESNO1||'-'||RESNO2 RESNO
  FROM APPATBAT
 WHERE PATNO IN (
                )
 ORDER BY 1,2,3
