SELECT TO_CHAR(A.CUNTTIME,'YYYY-MM-DD') CUNTTIME, A.EXAMPART, A.GUBUN, A.REPLYID, A.EXAMCODE, B.ORDNAME, SUBSTR(A.PATNO,1,5)||'***' PATNO, A.CUNTTEXT, A.REPLYTEXT
  FROM SMRTCNST A, MMORDRCT B
 WHERE CUNTTIME BETWEEN TO_dATE('20140601','YYYYMMDD') AND TO_dATE('20141130','YYYYMMDD')+0.99999
   AND EXAMPART = 'REC'
   AND GUBUN = 'GG'
   AND REPLYID = '207824'
   AND A.EXAMCODE = B.ORDCODE
 ORDER BY 1,7;
