-- 최종
SELECT DISTINCT A.ORDEPTDATE, A.PATNO, A.PATNAME, A.AGE, A.PKGCODE, B.ORDCODE, C.ORDNAME
  FROM (-- 대상자
        SELECT A.PATNO, A.ORDEPTDATE, A.PKGCODE, B.PATNAME, TRUNC(MONTHS_BETWEEN(A.ORDEPTDATE,B.BIRTHDAY)/12) AGE
          FROM SMRSV00T A, APPATBAT B
         WHERE A.ORDEPTDATE BETWEEN TO_dATE('20150102','YYYYMMDD') AND TO_dATE('20150531','YYYYMMDD')
           AND A.CANCELTIME IS NULL
           AND A.PKGCODE LIKE 'MM%'
           AND A.PATNO = B.PATNO
       ) A
     , MMMEDORT B
     , MMORDRCT C
 WHERE A.AGE > '64'
   AND A.PATNO = B.PATNO
   AND B.ORDDATE < TRUNC(SYSDATE)
   AND B.ORDCODE in ('XPNE13A', 'XPNEU')
   AND B.DCYN != 'Y'
   AND B.DGRTNFG IS NULL
   AND B.ORDCODE = C.ORDCODE
 ORDER BY 1,2
