--부인과, 치과검사
SELECT '1.검사및판독' GUBUN, TO_CHAR(A.EXECTIME,'YYYY-MM') "MONTHS", A.GUBUN2, A.PATFG, A.EXAM, A.ORDNAME, A.MEDCENTER, A.DR, COUNT(A.CNT) CNT
  FROM (
-- MD
--검사실별 의사별 검사 건수, 다시 수정 2009.12.01
-- 김영주 방사선사 요청으로 인해 PM기준시간을 1300 -> 1200으로 변경함. 2010.09월 통계부터~~~
SELECT A.EXECTIME
     , DECODE(TO_CHAR(A.EXECTIME,'D'),'1','주말','7','주말','주중') GUBUN2
     , A.ORDCODE EXAM, B.ORDNAME,
--       TO_CHAR(A.EXECTIME,'HH24:MI') "TIME",
       CASE WHEN TO_CHAR(A.EXECTIME,'HH24MI') < '1200' THEN 'AM'
       ELSE 'PM' END "APM",
       A.PATFG,
       A.MEDLOCATFG MEDCENTER,
       A.READDR1||'-'||C.USERNAME DR,
       COUNT(A.PATNO)  CNT
  FROM MMEXMORT A, MMORDRCT B, CSUSERMT C
 WHERE A.EXECTIME BETWEEN TO_dATE(&D1,'YYYYMMDD') AND TO_dATE(&D2,'YYYYMMDD')+.99999
   AND A.ORDCODE IN ('SM1801','SM1805','SM2001')
   AND A.PATFG = 'G'
   AND A.ORDCODE = B.ORDCODE
   AND A.READDR1 = C.USERID
 GROUP BY A.EXECTIME
       , DECODE(TO_CHAR(A.EXECTIME,'D'),'1','주말','7','주말','주중')
       , A.ORDCODE, B.ORDNAME,
--       TO_CHAR(A.EXECTIME,'HH24:MI') ,
       CASE WHEN TO_CHAR(A.EXECTIME,'HH24MI') < '1200' THEN 'AM'
       ELSE 'PM' END ,
       A.PATFG,
       A.MEDLOCATFG,
       A.READDR1||'-'||C.USERNAME
       ) A
 GROUP BY TO_CHAR(A.EXECTIME,'YYYY-MM'), A.GUBUN2, A.PATFG, A.EXAM, A.ORDNAME, A.MEDCENTER, A.DR;
