SELECT '1.GXT 검사' GUBUN, A.MEDLOCATFG, TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTH", COUNT(A.PATNO) CNT
  FROM SMRSV00T A, MMEXMORT B
 WHERE A.ORDDATE BETWEEN TO_DATE('20140101','YYYYMMDD') AND TO_DATE('20141130','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PATNO = B.PATNO
   AND A.ORDDATE = B.ORDDATE
   AND B.ORDCODE IN ('BS2401','SM3600')
   AND B.PROCSTAT > 'C'
 GROUP BY A.MEDLOCATFG, TO_CHAR(A.ORDDATE,'YYYY-MM')

SELECT '2.특화 및 스포츠 외래' GUBUN, A.MEDLOCATFG, TO_CHAR(A.ORDDATE,'YYYY-MM') "MONTH", COUNT(A.PATNO) CNT
  FROM SMRSV00T A, SMPKGMST B
 WHERE A.ORDDATE BETWEEN TO_DATE('20140101','YYYYMMDD') AND TO_DATE('20141130','YYYYMMDD')
   AND A.CANCELTIME IS NULL
   AND A.PKGCODE = B.PKGCODE
   AND B.PKGTYP IN ('5A','7')
--   AND NOT EXISTS (
--                   SELECT 'Y'
--                     FROM SMRSV00T X, MMEXMORT Y
--                    WHERE A.PATNO = X.PATNO
--                      AND A.ORDDATE = X.ORDDATE
--                      AND X.PATNO = Y.PATNO
--                      AND X.ORDDATE = Y.ORDDATE
--                      AND Y.ORDCODE IN ('BS2401','SM3600')
--                      AND Y.PROCSTAT > 'C'
--                  )
 GROUP BY A.MEDLOCATFG, TO_CHAR(A.ORDDATE,'YYYY-MM')
